### ISSUE TITLE
default behavior is broken for render  :action_name

### ISSUE THREAD

**Issue by fluxsaas** [madadam/liquidizer#2]
doesnt work:

```
render :show
```

works:

```
render :action => :show
```

error is:

```
undefined method `[]' for :show:Symbol
liquidizer-0.5.3/lib/liquidizer/controller_extensions.rb:49:in `liquid_template_for_view'
liquidizer-0.5.3/liquidizer/controller_extensions.rb:20:in `render'
```

**Comment by madadam** [comment]
Yes, I know about this. It's even in the TODO section of the README :) It's unlikely I fix it anytime soon (no time + the issue is not critical for me). But if you (or someone) send me a patch/pull request (with tests!), I'll include it.
